import { ProductType } from "./product-type";

export const ProductDate: ProductType[] = [
  {
    id: "1",
    brand: "Porsche",
    model: "911 Gt3 Rs",
    imageSrc: "https://imgur.com/BrwAy5s.png",
    power: 480,
    speed: 307,
    color: ["#CBD4DB", "#112A61", "#901212"],
    acceleration: 3.2,
    engineType: "engine",
    engineVolume: 4.0,
    price: 309000,
    discount: 0,
  },
  {
    id: "2",
    brand: "Porsche",
    model: "Macan S",
    imageSrc: "https://imgur.com/uwWyafZ.png",
    power: 380,
    speed: 259,
    color: ["#901212"],
    acceleration: 4.8,
    engineType: "engine",
    engineVolume: 3.0,
    price: 135000,
    discount: 10,
  },
  {
    id: "3",
    brand: "Porsche",
    model: "911 Turbo",
    imageSrc: "https://imgur.com/FDLuqkt.png",
    power: 580,
    speed: 320,
    color: ["#0C0D0F"],
    acceleration: 2.8,
    engineType: "engine",
    engineVolume: 3.8,
    price: 256000,
    discount: 0,
  },
  {
    id: "4",
    brand: "Porsche",
    model: "Taycan Turbo",
    imageSrc: "https://imgur.com/N4CCDTV.png",
    power: 707,
    speed: 250,
    color: ["#707277"],
    acceleration: 2.7,
    engineType: "electro",
    batteryCapacity: 93.4,
    price: 151000,
    discount: 10,
  },
  {
    id: "5",
    brand: "Porsche",
    model: "Panamera GTS",
    imageSrc: "https://imgur.com/YL1I4M3.png",
    power: 500,
    speed: 302,
    color: ["#8F0E22"],
    acceleration: 3.8,
    engineType: "engine",
    engineVolume: 4.0,
    price: 150000,
    discount: 0,
  },
  {
    id: "6",
    brand: "Porsche",
    model: "Taycan 4s",
    imageSrc: "https://imgur.com/Me9QTFU.png",
    power: 462,
    speed: 250,
    color: ["#695E68"],
    acceleration: 3.7,
    engineType: "electro",
    batteryCapacity: 93.4,
    price: 243000,
    discount: 0,
  },
];
